export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_SUCCESS';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const FETCH_USER_BY_USERNAME_SUCCESS = 'FETECH_USER_BY_USERNAME_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CREATE_NEW_SUCCESS = 'CREATE_NEW_SUCCESS';

export const ADD_HOUSE_SUCCESS = 'ADD_HOUSE_SUCCESS';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const SET_HOUSE_SUCCESS = 'SET_HOUSE_SUCCESS';
